server:
  port: 8080

spring:
  application:
    name: client
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
  main:
    allow-bean-definition-overriding: true #feign容易重复bean名，所以配置使其可以覆盖
eureka:
  client:
    #是否将自己注册进eureka server 默认为true
    register-with-eureka: true
    # 是否从Eureka server抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置成ture才能配合ribbon的负载均衡
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    prefer-ip-address: true
    instance-id: client8080

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000  #熔断超时时间

logging:
  level:
    #fegin以什么级别监控哪个接口
    com.atguigu.springcloud.service.PaymentFeignService: debug