server:
  port: 8010

spring:
  application:
    name: order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource     #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver       #mysql驱动包
    url: jdbc:mysql://localhost:3306/orderingsystem?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

eureka:
  client:
    register-with-eureka: true #是否将自己注册进eureka server 默认为true
    # 是否从Eureka server抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置成ture才能配合ribbon的负载均衡
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: order8010
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒 默认30
    lease-renewal-interval-in-seconds: 30
    #Eureka服务端在收到最后一次心跳后等待的时间上限，单位为秒 默认90 超时会被剔除
    lease-expiration-duration-in-seconds: 90

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.oop.entities #所有entity别名类所在包




